version: '3.5'

networks:
  storage:
    name: storage

volumes:
  redis_data:
    driver: local

services:
  app:
    build: .
    image: dummy_app:dev
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - '8080:8080'
    restart: always
    networks:
      - storage

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - storage
